set (FFMEDIA_LIBRARY ffmedia)

get_property (GLOBAL_CPP_VERSION            GLOBAL PROPERTY GLOBAL_CPP_VERSION)
get_property (GLOBAL_FFMEDIA_INCLUDE_DIR    GLOBAL PROPERTY FFMEDIA_INCLUDE_DIR)
get_property (GLOBAL_FFMEDIA_LIB_DIR        GLOBAL PROPERTY FFMEDIA_LIB_DIR)
get_property (GLOBAL_FFMEDIA_BIN_DIR        GLOBAL PROPERTY FFMEDIA_BIN_DIR)
get_property (GLOBAL_FFMEDIA_THIRDPARTY_DIR GLOBAL PROPERTY FFMEDIA_THIRDPARTY_DIR)
get_property (GLOBAL_FFMEDIA_TEST_DIR       GLOBAL PROPERTY FFMEDIA_TEST_DIR)
